### ISSUE TITLE
Occationally stops emiting data to graphite

### ISSUE THREAD

**Issue by davidc0le** [pandemicsyn/statsdpy#6]
We regularly find that statsdpy stops emitting graphite data. strace on the process shows it receiving UDP datagrams but a tcpdump on the IP of our graphite server shows no flushes going on.  If I restart the deamon the flushes apprear in tcpdump and all is good again.

OS: Ubuntu 12.04
Version: python-statsdpy 0.0.11-1
from https://github.com/pandemicsyn/statsdpy/releases/tag/0.0.11

The full config is below.  Any thoughs on how to debug this ? 

Thanks
David.

```
# cat /etc/statsdpy/statsdpy.conf | grep -v ^#
[main]
graphite_host = 10.x.x.x
graphite_port = 2003
graphite_pickle_port = 2004
listen_addr = 127.0.0.1
listen_port = 8125
pickle_protocol = no
pickle_batch_size = 300

debug = no

flush_interval = 10
percent_threshold = 90

legacy_namespace = false
global_prefix = storage.analytics
prefix_counter = counters.lon.the-server-host-name
prefix_timer = timers.lon.the-server-host-name
prefix_gauge = gauges.lon..the-server-host-name
```

**Comment by pandemicsyn** [comment]
I've actually had it happen a handful of times as well but it only ever happened on one of the 6 instances we run so I kinda wrote it off as system gremlins. Looking now though I realize that the other instances are running a slightly older version. Let me poke around and see what I can find.

**Comment by pandemicsyn** [comment]
I pushed up a new version, if it timed out talking to graphite it could have bubbled up an uncaught exception that killed the function that periodically reports stats. At the very least this change _should_ let statsdpy recover and report the next batch if something unexpected occurs.

If this does not seem to fix it for you or if you see any new errors logged feel free to leave another comment. In the mean time I'll get to work on getting some proper/working unit tests.

**Comment by davidc0le** [comment]
Thanks - that sounds like a few steps in the right direction

**Comment by davidc0le** [comment]
Thanks. 0.0.12 has been more reliable for us over the past 2 weeks compared with the previous 2 weeks on 0.0.11.
