### ISSUE TITLE
Init script looks at wrong path for config

### ISSUE THREAD

**Issue by elreydetodo** [pandemicsyn/statsdpy#9]
The init script refers to a different config file path than the readme says to put the config in. One of them should be fixed. I vote for using /etc/statsdpy/, as /etc/statsd/ (what the init script expects) is a reference to the wrong project's name.

**Comment by pandemicsyn** [comment]
Yep, you're totally right. Switching it to /etc/statsdpy's the right route. Do you wanna send a pull request? If not, ill push up a fix this afternoon.

**Comment by elreydetodo** [comment]
Filed [pull request 10](https://github.com/pandemicsyn/statsdpy/pull/10).

**Comment by pandemicsyn** [comment]
Thanks for the pull request!
